export interface MatrimonyProfile {
  id: string
  name: string
  age: number
  education: string
  profession: string
  location: string
  community?: string
  photos: string[]
  bio?: string
  interests?: string[]
  verified?: boolean
  premium?: boolean
}

export const MOCK_MATRIMONY_PROFILES: MatrimonyProfile[] = [
  {
    id: "m1",
    name: "Aditi Sharma",
    age: 27,
    education: "MBA, IIM Ahmedabad",
    profession: "Product Manager",
    location: "Bengaluru, India",
    community: "Brahmin",
    photos: ["/professional-woman-smiling.png", "/woman-hiking.png"],
    bio: "Family-oriented person who loves traveling and cooking. Looking for someone who values traditions and is ready for marriage.",
    interests: ["Travel", "Cooking", "Dancing", "Reading"],
    verified: true,
    premium: false,
  },
  {
    id: "m2",
    name: "Rahul Mehta",
    age: 30,
    education: "B.Tech, IIT Bombay",
    profession: "Senior Software Engineer",
    location: "Pune, India",
    community: "Vaishya",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Tech enthusiast who enjoys hiking and photography. Seeking a life partner who shares similar values and dreams.",
    interests: ["Technology", "Photography", "Hiking", "Music"],
    verified: true,
    premium: true,
  },
  {
    id: "m3",
    name: "Priya Patel",
    age: 25,
    education: "M.D., AIIMS Delhi",
    profession: "Doctor",
    location: "Mumbai, India",
    community: "Patel",
    photos: ["/professional-woman-smiling.png", "/woman-at-coffee-shop.png"],
    bio: "Dedicated doctor with a passion for helping others. Looking for a caring partner who understands the demands of my profession.",
    interests: ["Medicine", "Yoga", "Classical Music", "Volunteering"],
    verified: true,
    premium: false,
  },
  {
    id: "m4",
    name: "Arjun Singh",
    age: 32,
    education: "CA, ICAI",
    profession: "Chartered Accountant",
    location: "Delhi, India",
    community: "Rajput",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Finance professional who believes in work-life balance. Enjoys cricket and classical music. Seeking a life partner for a meaningful relationship.",
    interests: ["Cricket", "Classical Music", "Finance", "Travel"],
    verified: true,
    premium: true,
  },
  {
    id: "m5",
    name: "Sneha Reddy",
    age: 28,
    education: "M.Tech, IISc Bangalore",
    profession: "Data Scientist",
    location: "Hyderabad, India",
    community: "Reddy",
    photos: ["/professional-woman-smiling.png", "/woman-hiking.png"],
    bio: "Data science professional who loves solving complex problems. Enjoys reading, cooking, and spending time with family.",
    interests: ["Data Science", "Reading", "Cooking", "Family Time"],
    verified: true,
    premium: false,
  },
  {
    id: "m6",
    name: "Vikram Gupta",
    age: 29,
    education: "MBA, XLRI Jamshedpur",
    profession: "Investment Banker",
    location: "Mumbai, India",
    community: "Gupta",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Investment banker with a passion for finance and economics. Looking for an intelligent and ambitious life partner.",
    interests: ["Finance", "Economics", "Golf", "Wine Tasting"],
    verified: true,
    premium: true,
  },
  {
    id: "m7",
    name: "Kavya Iyer",
    age: 26,
    education: "B.Tech, NIT Trichy",
    profession: "Software Engineer",
    location: "Chennai, India",
    community: "Iyer",
    photos: ["/professional-woman-smiling.png", "/woman-at-coffee-shop.png"],
    bio: "Software engineer who loves coding and technology. Enjoys Bharatanatyam dancing and South Indian classical music.",
    interests: ["Coding", "Bharatanatyam", "Classical Music", "Technology"],
    verified: true,
    premium: false,
  },
  {
    id: "m8",
    name: "Rohit Agarwal",
    age: 31,
    education: "B.Com, Delhi University",
    profession: "Business Owner",
    location: "Delhi, India",
    community: "Agarwal",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Successful entrepreneur running a textile business. Values family traditions and is looking for a traditional yet modern life partner.",
    interests: ["Business", "Family Traditions", "Cricket", "Travel"],
    verified: true,
    premium: true,
  },
  {
    id: "m9",
    name: "Ananya Joshi",
    age: 24,
    education: "B.A. Psychology, Lady Shri Ram College",
    profession: "Clinical Psychologist",
    location: "Delhi, India",
    community: "Joshi",
    photos: ["/professional-woman-smiling.png", "/woman-hiking.png"],
    bio: "Clinical psychologist helping people with mental health. Loves reading, painting, and spending time in nature.",
    interests: ["Psychology", "Reading", "Painting", "Nature"],
    verified: true,
    premium: false,
  },
  {
    id: "m10",
    name: "Siddharth Malhotra",
    age: 33,
    education: "LLB, National Law School",
    profession: "Corporate Lawyer",
    location: "Mumbai, India",
    community: "Malhotra",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Corporate lawyer specializing in mergers and acquisitions. Enjoys playing tennis and watching movies in his free time.",
    interests: ["Law", "Tennis", "Movies", "Reading"],
    verified: true,
    premium: true,
  },
  {
    id: "m11",
    name: "Divya Nair",
    age: 27,
    education: "M.Sc. Chemistry, IIT Madras",
    profession: "Research Scientist",
    location: "Bangalore, India",
    community: "Nair",
    photos: ["/professional-woman-smiling.png", "/woman-at-coffee-shop.png"],
    bio: "Research scientist working on sustainable chemistry solutions. Passionate about environmental conservation and classical dance.",
    interests: ["Research", "Environment", "Classical Dance", "Science"],
    verified: true,
    premium: false,
  },
  {
    id: "m12",
    name: "Amit Kumar",
    age: 30,
    education: "B.Tech, IIT Delhi",
    profession: "Tech Lead",
    location: "Gurgaon, India",
    community: "Kumar",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Tech lead at a leading startup. Loves building products that make a difference. Enjoys playing guitar and hiking.",
    interests: ["Technology", "Guitar", "Hiking", "Startups"],
    verified: true,
    premium: true,
  },
  {
    id: "m13",
    name: "Shruti Desai",
    age: 25,
    education: "M.A. English, JNU",
    profession: "Content Writer",
    location: "Pune, India",
    community: "Desai",
    photos: ["/professional-woman-smiling.png", "/woman-hiking.png"],
    bio: "Creative content writer who loves storytelling. Enjoys reading, writing poetry, and exploring new cafes around the city.",
    interests: ["Writing", "Poetry", "Reading", "Cafes"],
    verified: true,
    premium: false,
  },
  {
    id: "m14",
    name: "Rajesh Verma",
    age: 34,
    education: "M.Sc. Physics, IIT Kanpur",
    profession: "Physics Professor",
    location: "Kolkata, India",
    community: "Verma",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Physics professor who loves teaching and research. Enjoys playing chess, reading science fiction, and classical music.",
    interests: ["Physics", "Chess", "Science Fiction", "Classical Music"],
    verified: true,
    premium: true,
  },
  {
    id: "m15",
    name: "Pooja Shah",
    age: 28,
    education: "B.Tech, VJTI Mumbai",
    profession: "UX Designer",
    location: "Mumbai, India",
    community: "Shah",
    photos: ["/professional-woman-smiling.png", "/woman-at-coffee-shop.png"],
    bio: "UX designer passionate about creating user-friendly experiences. Loves art, design, and exploring new places.",
    interests: ["Design", "Art", "Travel", "User Experience"],
    verified: true,
    premium: false,
  },
  {
    id: "m16",
    name: "Deepak Jain",
    age: 32,
    education: "CA, ICAI",
    profession: "Tax Consultant",
    location: "Jaipur, India",
    community: "Jain",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Tax consultant helping businesses with compliance. Values simplicity and honesty. Enjoys meditation and classical music.",
    interests: ["Taxation", "Meditation", "Classical Music", "Business"],
    verified: true,
    premium: true,
  },
  {
    id: "m17",
    name: "Meera Krishnan",
    age: 26,
    education: "M.A. Economics, Delhi School of Economics",
    profession: "Economic Analyst",
    location: "Delhi, India",
    community: "Krishnan",
    photos: ["/professional-woman-smiling.png", "/woman-hiking.png"],
    bio: "Economic analyst working on policy research. Loves analyzing data and trends. Enjoys classical dance and reading.",
    interests: ["Economics", "Data Analysis", "Classical Dance", "Reading"],
    verified: true,
    premium: false,
  },
  {
    id: "m18",
    name: "Nikhil Tiwari",
    age: 29,
    education: "B.Tech, BITS Pilani",
    profession: "Product Manager",
    location: "Bangalore, India",
    community: "Tiwari",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Product manager at a fintech company. Passionate about building products that solve real problems. Loves playing cricket.",
    interests: ["Product Management", "Cricket", "Fintech", "Problem Solving"],
    verified: true,
    premium: true,
  },
  {
    id: "m19",
    name: "Riya Agarwal",
    age: 24,
    education: "B.Tech, IIT Roorkee",
    profession: "Software Developer",
    location: "Gurgaon, India",
    community: "Agarwal",
    photos: ["/professional-woman-smiling.png", "/woman-at-coffee-shop.png"],
    bio: "Software developer who loves coding and technology. Enjoys dancing, cooking, and spending time with family and friends.",
    interests: ["Coding", "Dancing", "Cooking", "Technology"],
    verified: true,
    premium: false,
  },
  {
    id: "m20",
    name: "Karan Singh",
    age: 35,
    education: "MBA, IIM Calcutta",
    profession: "Marketing Director",
    location: "Mumbai, India",
    community: "Singh",
    photos: ["/professional-headshot.png", "/casual-outdoor-photo.jpg"],
    bio: "Marketing director with 10+ years of experience. Loves traveling, photography, and exploring different cultures. Looking for a life partner to share adventures with.",
    interests: ["Marketing", "Travel", "Photography", "Culture"],
    verified: true,
    premium: true,
  },
]
